prepsys: rework the script from ground up
Script is meant now to be run as root when installing a system.
Another improvements:
- Make functions reentrable.
- Create docker-compose file for testing.
- sync-pkgs functions now return 0 if nothing has been done

diff --git a/.local/scripts/prepsys b/.local/scripts/prepsys
--- a/.local/scripts/prepsys
+++ b/.local/scripts/prepsys
@@ -1,22 +1,32 @@
 #!/bin/bash
 
+# TODO
+# greeter home needs to be created (/var/lib/greeter) for greetd
 
-DIR_SUCKLESS="${HOME}/.local/suckless"
-DIR_NVIM="${HOME}/.config"
 
-DIR_SCRIPT="$(dirname "$0")"
-NAME_SCRIPT="$(basename "$0")"
-PATH_RSA_KEY="${HOME}/.ssh/id_rsa"
+MAKEFLAGS="-j$(nproc)"
+export MAKEFLAGS
 
 print_help() {
-	echo "Usage: $NAME_SCRIPT [OPTIONS] FILE"
+	echo "Usage: $(basename "$0") [OPTIONS] FILES..."
 	echo "Configure system for optimal use"
-	echo "Supply FILE as a list of packages that you want to install"
+	echo "Supply FILES contating lists of packages that you want to install"
 	echo
 	echo "Options:"
 	echo "-h, --help      Show brief help"
-	echo "-t, --tlp       Install tlp (laptop battery management system)"
+	echo "-u, --user      Specify user's name"
+	echo "-p, --password  Specify user's password"
+	echo "-H, --hostname  Specify hostname"
+	echo "-n, --notebook  Use as notebook (install power management tools)"
 	exit 127
+}
+
+max() {
+	out=$1
+	for i in "$@"; do
+		((i > out)) && out=$i
+	done
+	echo "$out"
 }
 
 prompt_and_remove_path() {
@@ -31,129 +41,177 @@ prompt_and_remove_path() {
 	fi
 }
 
-install_yay() {
-	pacman -Qq | grep -q yay && return
-	sudo pacman -Syu --needed --noconfirm git openssh base-devel || return
-	(
-		cd "$DIR_SCRIPT" &&
-			git clone https://aur.archlinux.org/yay.git &&
-			cd yay &&
-			makepkg -si --needed --noconfirm &&
-			cd .. &&
-			rm -rf yay/ || return
-	)
-}
-
-print_github_key() {
-	PATH_RSA_KEY_GITHUB="${HOME}/github_key.pub"
-	cp "${PATH_RSA_KEY}.pub" "${PATH_RSA_KEY_GITHUB}"
-	printf '%s\n' \
-		"A copy of an rsa public key has been added to ${PATH_RSA_KEY_GITHUB}" \
-		"Please add this key to github.com"
-}
-
-check_rsa() {
-	[ -f "$PATH_RSA_KEY" ] && return
-	ssh-keygen -t rsa -b 4096 -C 'jirik.sz@gmail.com' -P '' -f "$PATH_RSA_KEY"
-}
+################################################################################
 
 init_dotfiles_repo() {
-	PATH_REPO="${HOME}/.dotfiles.git"
-	prompt_and_remove_path "$PATH_REPO" || return 0
-	sudo pacman -Syu --needed --noconfirm openssh git &&
-		git clone --bare --recurse-submodules https://github.com/Jirixek/dotfiles.git "$PATH_REPO" &&
+	[ -d "$dir_dotfiles" ] && return 0
+	sudo -iu "$new_user" -- sh -s <<-"EOF"
+		PATH_REPO="${HOME}/.dotfiles.git"
+		git clone --bare https://gitlab.com/jirixek/dotfiles.git "$PATH_REPO" &&
 		git --git-dir="$PATH_REPO" --work-tree="$HOME" checkout -f &&
 		git --git-dir="$PATH_REPO" config --local status.showUntrackedFiles no &&
-		git --git-dir="$PATH_REPO" remote set-url origin git@github.com:Jirixek/dotfiles.git &&
-		check_rsa &&
-		rm -f ~/.bash_login || return
+		git --git-dir="$PATH_REPO" remote set-url origin git@gitlab.com:jirixek/dotfiles.git &&
+		rm -f ~/.bash_login
+	EOF
+}
+
+init_suckless_repo() {
+	[ -d "$dir_suckless" ] && return 0
+	sudo -u "$new_user" -- sh -s <<-EOF
+		make -C "$dir_suckless" clone
+	EOF
+}
+
+init_nvim_repo() {
+	[ -d "$dir_nvim" ] && return 0
+	sudo -u "$new_user" -- sh -s <<-EOF
+		git clone 'https://gitlab.com/jirixek/vim.git' "$dir_nvim" &&
+		git -C "$dir_nvim" remote set-url origin 'git@gitlab.com:jirixek/vim.git'
+	EOF
+}
+
+init_git_repos() {
+	init_dotfiles_repo
+	exit_dotfiles=$?
+
+	init_suckless_repo
+	exit_suckless=$?
+
+	init_nvim_repo
+	exit_nvim=$?
+
+	return "$(max $exit_dotfiles $exit_suckless $exit_nvim)"
+}
+
+install_yay() {
+	pacman -Qq | grep -q yay && return 0
+	sudo -u "$new_user" -- sh -s <<-"EOF"
+		YAY_DIR="$(mktemp -d)" &&
+		git clone https://aur.archlinux.org/yay.git "$YAY_DIR" &&
+		cd "$YAY_DIR" &&
+		makepkg -si --needed --noconfirm
+		exit_yay=$?
+		rm -rf "$YAY_DIR"
+		exit $exit_yay
+	EOF
 }
 
 init_services() {
-	# Bash suggestions for unknown packages
-	# Bluetooth
-	# Cron
-	# Firefox profile in memory
-	# Lock screen after suspend
-
-	sudo systemctl enable \
-		pkgfile-update.timer \
+	# pkgfile-update: Bash suggestions for unknown packages
+	# fstrim: Trim blocks which are not in use by the filesystem
+	systemctl enable \
+		NetworkManager.service \
 		bluetooth.service \
 		cronie.service \
-		fstrim.timer \
-		slock@jirik.service
+		docker.socket \
+		pkgfile-update.timer \
+		fstrim.timer
 	exit_root=$?
 
-	systemctl --user enable \
+	# psd: Firefox profile in memory
+	sudo -u "$new_user" -- systemctl --user enable \
 		psd.service \
 		mpd.service \
 		syncthing.service \
 		geoclue-agent.service
 	exit_user=$?
 
-	return $((exit_root > exit_user ? exit_root : exit_user))
+	return "$(max $exit_root $exit_user)"
 }
 
-init_git_repos() {
-	# Suckless
-	REPOS_SUCKLESS=('dmenu' 'dwm' 'dwmblocks' 'slock' 'st')
-	(
-		cd "$DIR_SUCKLESS" || return
-		for repo in "${REPOS_SUCKLESS[@]}"; do
-			git clone "https://github.com/Jirixek/${repo}.git" "$repo"
-			git --git-dir="$repo" remote set-url origin "git@github.com:Jirixek/${repo}.git"
-		done
-	)
+init_grub() {
+	grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
+	grub-mkconfig -o /boot/grub/grub.cfg
+}
 
-	# Nvim
-	(
-		cd "$DIR_NVIM" || return
-		git clone 'https://github.com/Jirixek/vim.git' 'nvim'
-		git --git-dir='nvim' remote set-url origin "git@github.com:Jirixek/vim.git"
-	)
+init_locale() {
+	sed -i 's/^#en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/;
+	        s/^#cs_CZ.UTF-8 UTF-8$/cs_CZ.UTF-8 UTF-8/' /etc/locale.gen
+	locale-gen
+}
+
+init_hostname() {
+	echo "$new_hostname" >/etc/hostname
+}
+
+init_timezone() {
+	ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime
+	hwclock --systohc
+}
+
+init_sudoers() {
+	# Grant sudo access to wheel group
+	sed -i 's/^# %wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/' /etc/sudoers
 }
 
 link_dash() {
-	# change sh shell to dash
-	sudo ln -sf /bin/dash /bin/sh
+	ln -sf /bin/dash /bin/sh
 }
 
-add_user_to_groups() {
-	sudo usermod -aG wireshark,rfkill,uucp,audio,geoclue,openvpn,docker "$USER"
+create_user() {
+	getent passwd jirik && return 0
+	useradd -m "$new_user" -g wheel
 }
 
-install_suckless_tools() {
-	(
-		cd "$DIR_SUCKLESS" || return
-		make checkout
-		make install
-	)
+set_user_groups() {
+	usermod -aG wireshark,rfkill,uucp,audio,geoclue,openvpn,docker "$new_user"
 }
 
 move_gpg_folder() {
-	cp -r "${HOME}/.gnupg/*" "${HOME}/.local/share/gnupg/"
-	rm -r "${HOME}/.gnupg"
+	sudo -iu "$new_user" -- sh -s <<-"EOF"
+		[ ! -d "${HOME}/.gnupg" ] && exit 0
+		cp -pr "${HOME}/.gnupg/*" "${HOME}/.local/share/gnupg/" &&
+		rm -r "${HOME}/.gnupg"
+	EOF
 }
 
-main() {
-	if [ "$(id -u)" -eq 0 ]; then
-		echo "Please don't run as root." >&2
-		exit 1
-	fi
+install_suckless() {
+	sudo -u "$new_user" -- sh -s <<-EOF
+		make -C "$dir_suckless" checkout &&
+		make -C "$dir_suckless" install
+	EOF
+}
 
-	FILE_PACKAGES=""
+config_as_notebook() {
+	pacman -Syu --needed --noconfirm tlp tlp-rdw &&
+	systemctl enable tlp.service NetworkManager-dispatcher.service
+}
+
+################################################################################
+
+cleanup() {
+	rm -f /etc/sudoers.d/prepsys
+	exit
+}
+trap cleanup HUP INT QUIT TERM PWR EXIT
+
+main() {
+	file_packages=()
 	while [ "$#" -gt 0 ]; do
 		case "$1" in
 			-h | --help) print_help ;;
-			-t | --tlp)
-				sudo pacman -Syu --needed --noconfirm tlp tlp-rdw &&
-					sudo systemctl enable tlp.service NetworkManager-dispatcher.service &&
-					sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket || exit
+			-n | --notebook)
+				is_notebook=1
+				shift
+				;;
+			-u | --user)
+				new_user="$2"
+				shift 2
+				;;
+			-p | --password)
+				new_passwd="$2"
+				shift 2
+				;;
+			-H | --hostname)
+				new_hostname="$2"
+				shift 2
+				;;
+			--)
 				shift
 				;;
 			*)
-				if [ -z "$FILE_PACKAGES" ] && [ -f "$1" ]; then
-					FILE_PACKAGES="$1"
+				if [ -f "$1" ]; then
+					file_packages+=("$1")
 				else
 					print_help
 				fi
@@ -162,17 +220,41 @@ main() {
 		esac
 	done
 
-	[ -z "$FILE_PACKAGES" ] && print_help
+	[ "${#file_packages[@]}" -eq 0 ] && print_help
+
+	pacman -Syu --needed --noconfirm sudo git make openssh base-devel
+
+	create_user "$new_user"
+	printf '%s\n' "root:$new_passwd" "$new_user:$new_passwd" | chpasswd
+
+	new_home="$(getent passwd "$new_user" | cut -d: -f6)"
+	dir_suckless="${new_home}/.local/suckless"
+	dir_nvim="${new_home}/.config/nvim"
+	dir_dotfiles="${new_home}/.dotfiles.git"
+
+	# Deleted in cleanup() function
+	echo '%wheel ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/prepsys
 
 	init_git_repos &&
-		install_yay &&
-		"$HOME"/.local/bin/sync-pkgs "$FILE_PACKAGES" &&
-		"$HOME"/.local/bin/sync-conf -w &&
-		init_services &&
-		link_dash &&
-		add_user_to_groups &&
-		move_gpg_folder &&
-		print_github_key || exit
+	install_yay &&
+	sudo -iu "$new_user" -- "${new_home}/.local/scripts/sync-pkgs" --noconfirm "${file_packages[@]}" &&
+	sudo -iu "$new_user" -- "${new_home}/.local/scripts/sync-conf" -w &&
+	install_suckless &&
+	init_services &&
+	# init_grub &&
+	init_locale &&
+	init_hostname &&
+	# init_timezone &&
+	init_sudoers &&
+	link_dash &&
+	set_user_groups &&
+	move_gpg_folder &&
+	[ "$is_notebook" = 1 ] && config_as_notebook
 }
+
+
+ARGS="$(getopt -o 'hnu:p:H:' --long 'help,notebook,user:,password:,hostname:' \
+	-n 'prepsys' -- "$@")" || print_help
+eval set -- "$ARGS"
 
 main "$@"
