sync-pkgs: print the option that is invalid

diff --git a/.local/scripts/sync-pkgs b/.local/scripts/sync-pkgs
--- a/.local/scripts/sync-pkgs
+++ b/.local/scripts/sync-pkgs
@@ -61,6 +61,7 @@ while [ "$#" -gt 0 ]; do
 			if [ -f "$1" ]; then
 				FILE_PKGS_TARGET+=("$1")
 			else
+				echo "Invalid option: $1" >&2
 				get_help
 			fi
 			shift
